# Generated by Django 4.0.6 on 2022-07-25 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_address_options_alter_customer_options_and_more'),
        ('contract', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'contract', 'verbose_name_plural': 'contracts'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='returnDateTime',
            field=models.DateTimeField(verbose_name='return date and time'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='returnedAt',
            field=models.DateTimeField(verbose_name='returned at'),
        ),
    ]
