# Generated by Django 4.0.6 on 2022-07-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_alter_contract_options_alter_contract_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='returnDateTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='return date and time'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='returnedAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='returned at'),
        ),
    ]
