# Generated by Django 4.0.6 on 2022-07-26 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_options_alter_car_license_alter_car_model_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0004_alter_contract_returndatetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='user',
        ),
        migrations.AddField(
            model_name='contract',
            name='amount_to_pay',
            field=models.IntegerField(default=0, verbose_name='amount to pay'),
        ),
        migrations.AddField(
            model_name='contract',
            name='building',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='paid_by',
            field=models.CharField(default='', max_length=255, verbose_name='paid by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='reference',
            field=models.CharField(default='', max_length=255, verbose_name='contract reference'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='cars.car'),
        ),
    ]
