# Generated by Django 4.0.6 on 2022-07-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_remove_contract_user_contract_amount_to_pay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='paid_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='paid by'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='contract reference'),
        ),
    ]
