# Generated by Django 4.0.6 on 2022-07-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='buidling_abbr',
            field=models.CharField(max_length=2, verbose_name='building abbr'),
        ),
        migrations.AlterField(
            model_name='user',
            name='building_name',
            field=models.TextField(max_length=500, verbose_name='building name'),
        ),
    ]
