# Generated by Django 4.0.6 on 2022-07-26 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_buidling_abbr_alter_user_building_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'building', 'verbose_name_plural': 'buildings'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='buidling_abbr',
            new_name='building_abbr',
        ),
    ]
