# Generated by Django 4.0.6 on 2022-07-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'car', 'verbose_name_plural': 'cars'},
        ),
        migrations.AlterField(
            model_name='car',
            name='license',
            field=models.CharField(max_length=200, verbose_name='license'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=200, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.CharField(max_length=200, verbose_name='owner'),
        ),
    ]
