# Generated by Django 4.0.6 on 2022-07-25 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_one', models.CharField(max_length=200)),
                ('line_two', models.CharField(max_length=200)),
                ('line_three', models.CharField(max_length=200)),
                ('line_four', models.CharField(max_length=200)),
                ('cont', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DrivingLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('issued_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.address')),
                ('driving_license', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers.drivinglicense')),
                ('passport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers.passport')),
            ],
        ),
    ]
