# Generated by Django 4.0.6 on 2022-07-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_address_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
