# Generated by Django 4.0.6 on 2022-07-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='cont',
        ),
        migrations.AddField(
            model_name='customer',
            name='cont',
            field=models.CharField(default=0, max_length=50, verbose_name='cont no'),
            preserve_default=False,
        ),
    ]
