# Generated by Django 4.0.6 on 2022-07-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_address_cont_customer_cont'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='blocked',
            field=models.BooleanField(default=False, verbose_name='blocked'),
        ),
    ]
